version: '3.2'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/joao/code/mongodb:/data/db

  api:
    build: .
    command: /start-reload.sh
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    # environment: 
      # PORT: "8080"
    ports:
      - 80:80
    links:
      - mongo
