version: '3.2'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - /srv/mongodb:/data/db

  api:
    build: .
    # command: /start-reload.sh
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    environment: 
      PORT: "8080"
    ports:
      - 8080:8080
    links:
      - mongo
